target "Everives_S" do
platform :ios,'7.0'
pod 'MBProgressHUD','~>0.8'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDAutoLayout'
pod 'RongCloudIMKit','~>2.5.2'
pod 'Qiniu','~>7.0'
pod 'AFNetworking'
pod 'AMap3DMap','3.3.2'
pod 'AMapSearch','3.3.0'
pod 'Pingpp/Alipay', '~> 2.1.0'
pod 'Pingpp/Wx', '~> 2.1.0'
end
